{"content": {"suites": {"0": {"status": {"total_pass": 0, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 2, "total_error": 0}, "tests": {"0": {"status": "FAIL", "message": "   socket.gaierror: [Errno 8] nodename nor servname provided, or not known\n       urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x101c97bb0>: Failed to resolve 'jsonplaceholder.typicode.com' ([Errno 8] nodename nor servname provided, or not known)\n       urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='jsonplaceholder.typicode.com', port=443): Max retries exceeded with url: /posts/1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x101c97bb0>: Failed to resolve 'jsonplaceholder.typicode.com' ([Errno 8] nodename nor servname provided, or not known)\"))\n       requests.exceptions.ConnectionError: HTTPSConnectionPool(host='jsonplaceholder.typicode.com', port=443): Max retries exceeded with url: /posts/1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x101c97bb0>: Failed to resolve 'jsonplaceholder.typicode.com' ([Errno 8] nodename nor servname provided, or not known)\"))\n", "test_name": "test_get_demo", "rerun": "0"}, "1": {"status": "FAIL", "message": "   socket.gaierror: [Errno 8] nodename nor servname provided, or not known\n       urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x101fb6dc0>: Failed to resolve 'jsonplaceholder.typicode.com' ([Errno 8] nodename nor servname provided, or not known)\n       urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='jsonplaceholder.typicode.com', port=443): Max retries exceeded with url: /posts (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x101fb6dc0>: Failed to resolve 'jsonplaceholder.typicode.com' ([Errno 8] nodename nor servname provided, or not known)\"))\n       requests.exceptions.ConnectionError: HTTPSConnectionPool(host='jsonplaceholder.typicode.com', port=443): Max retries exceeded with url: /posts (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x101fb6dc0>: Failed to resolve 'jsonplaceholder.typicode.com' ([Errno 8] nodename nor servname provided, or not known)\"))\n", "test_name": "test_post_demo", "rerun": "0"}}, "suite_name": "tests/test_postreq.py"}}}, "date": "November 06, 2024", "start_time": 1730913832.295947, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "0", "fail": "2", "skip": "0", "error": "0", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "2"}